---
version: 2
updates:
  # Enable version updates for terraform in the root directory
  - package-ecosystem: "terraform"
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
  # Enable version updates for terraform in the examples directory
  - package-ecosystem: "terraform"
    directory: "examples/complete"
    # Check for updates once a week
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "tests/complete"
    # Check for updates once a week
    schedule:
      interval: "weekly"
  - package-ecosystem: github-actions
    directory: ".github/workflows"
    schedule:
      interval: "weekly"
