---
name: terratest

on:
  pull_request:
    branches:
      - '*'

permissions: write-all

jobs:
  terratest:
    uses: flufi-io/workflows/.github/workflows/terratest.yaml@main
    with:
      ref: ${{ github.event.pull_request.head.sha }}
    secrets: inherit
