---
name: terraform pre-commit
on:
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

env:
  DOCKER_USERNAME: ${{ github.actor }}
  DOCKER_PASSWORD: ${{ secrets.GH_TOKEN }}

jobs:
  pre-commit:
    uses: flufi-io/workflows/.github/workflows/terraform_precommit.yaml@main
    with:
      ref: ${{ github.event.pull_request.head.sha }}
    secrets: inherit
